spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres


cryptography:
  encryption:
    key: ${ENCRYPTION_KEY}
    algorithm: AES-GCM
  pseudonymize:
    active: true
  gdpr-encryption:
    active: true
  logging-enabled: true