### Test 1 - Hire Employee with Valid Data
POST http://localhost:7000/employees
Content-Type: application/json

{
  "firstName": "Christoph",
  "emailAddress": "christoph.englisch@gmail.com",
  "lastName": "Englisch",
  "birthday": "1990-01-01",
  "role": "EMPLOYEE"
}

### Test 1 - Hire Employee with Valid Data
POST http://localhost:7000/employees
Content-Type: application/json

{
  "firstName": "Elias",
  "emailAddress": "elias.kist@web.de",
  "lastName": "Kist",
  "birthday": "1991-06-02",
  "role": "BACK_OFFICE"
}

### Test 2 - Hire Employee with Missing First Name
POST http://localhost:7000/employees
Content-Type: application/json

{
  "lastName": "Smith",
  "birthday": "1985-05-15",
  "role": "BACK_OFFICE"
}

### Test 3 - Hire Employee with Invalid Date Format
POST http://localhost:7000/employees
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Johnson",
  "birthday": "20-10-1992",
  "role": "EMPLOYEE"
}

### Test 4 - Hire Employee with Non-Existent Role
POST http://localhost:7000/employees
Content-Type: application/json

{
  "firstName": "Bob",
  "lastName": "Brown",
  "birthday": "1980-03-30",
  "role": "CEO"
}

### Test 5 - Hire Employee with Empty Payload
POST http://localhost:7000/employees
Content-Type: application/json

{}
